/**
 * GHotel
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationResponseDTO } from './reservationResponseDTO';
import { CustomerResponseDTO } from './customerResponseDTO';


export interface CustomerReservationsResponseDTO { 
    customer?: CustomerResponseDTO;
    reservations?: Array<ReservationResponseDTO>;
}

