/**
 * GHotel
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReservationRequestDTO { 
    customerId: string;
    checkIn: string;
    checkOut: string;
    details?: string;
}

