/**
 * GHotel
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationResponseDTO } from './reservationResponseDTO';
import { CustomerResponseDTO } from './customerResponseDTO';
import { RoomResponseDTO } from './roomResponseDTO';


export interface ReservationRoomsCustomerResponseDTO { 
    reservation?: ReservationResponseDTO;
    customer?: CustomerResponseDTO;
    rooms?: Array<RoomResponseDTO>;
}

