/**
 * GHotel
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationResponseDTO } from './reservationResponseDTO';
import { RoomResponseDTO } from './roomResponseDTO';


export interface RoomReservationsResponseDTO { 
    room?: RoomResponseDTO;
    reservations?: Array<ReservationResponseDTO>;
}

